# Generated by Django 6.0.7 on 2026-07-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='pagamento_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
