# Generated by Django 6.0.7 on 2026-07-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendamento_pagamento_id_agendamento_valor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['data', 'horario'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['nome'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.TimeField(verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='pagamento_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Pagamento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='agenda.servico', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao',
            field=models.PositiveIntegerField(verbose_name='Duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['data'], name='agenda_agen_data_ff2e69_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['status'], name='agenda_agen_status_b7ea8e_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(fields=('data', 'horario'), name='horario_unico'),
        ),
    ]
