# Generated by Django 6.0.7 on 2026-07-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_agendamento_options_alter_servico_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={},
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao',
            field=models.PositiveIntegerField(default=45, verbose_name='Duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
