# Generated by Django 6.0.7 on 2026-08-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_agendamento_atualizado_em_agendamento_pix_base64_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agendamento',
            name='agenda_agen_pagamen_9468bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='agendamento',
            name='agenda_agen_order_i_488ded_idx',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='pagamento_id',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='pix_base64',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='pix_code',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='pix_expiration',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='ticket_url',
        ),
    ]
