# Generated by Django 6.0.7 on 2026-08-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_remove_agendamento_agenda_agen_pagamen_9468bf_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('horario_inicio', models.TimeField(verbose_name='Horário inicial')),
                ('horario_fim', models.TimeField(verbose_name='Horário final')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloqueio Semanal',
                'verbose_name_plural': 'Bloqueios Semanais',
                'ordering': ['dia_semana', 'horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadeSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], unique=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Atende neste dia')),
                ('horario_inicio', models.TimeField(default='09:00', verbose_name='Início')),
                ('horario_fim', models.TimeField(default='18:00', verbose_name='Fim')),
            ],
            options={
                'verbose_name': 'Disponibilidade Semanal',
                'verbose_name_plural': 'Disponibilidade Semanal',
                'ordering': ['dia_semana'],
            },
        ),
    ]
